### ISSUE TITLE
[BUG] IS THIS WORKING FOR NEW UPDATE  It doesnt seem to work for me at all!

### ISSUE THREAD

**Issue by ImaSpeacialBoi** [Goobwabber/MultiplayerExtensions#148] opened 2021-10-10 21:33 UTC
**Multiplayer Extensions Version and Download Source**

**Your Platform**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Log**

**Screenshots/Video**

**Additional context**

**Comment by qe201020335** [comment] 2021-10-11 02:48
> Any helpful tips?

Wait.

Or fix it yourself

**Comment by ImaSpeacialBoi** [comment] 2021-10-11 03:07
> > Any helpful tips?
> 
> Wait.
> 
> Or fix it yourself
Look dude, I am trying to see if one of the most popular and game changing mods are gonna continue being supported, or if there are other versions of this type of mod being out. No one gives a shit about the base gaem, this is what makes the game fun. Its not an unreasonable question asshole.

**Comment by ImaSpeacialBoi** [comment] 2021-10-11 03:08
> This hasn't been updated in months? Idk what you expect from it tbh

Maybe other options?

**Comment by Goobwabber** [comment] 2021-10-29 18:52
Duplicate of #136

**Closed by Goobwabber** 2021-10-29 18:52 UTC
