### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by renegadechkn** [Goobwabber/MultiplayerExtensions#151] opened 2021-10-20 22:31 UTC
**Multiplayer Extensions Version and Download Source**
MultiplayerExtensions v0.5.4, github

**Your Platform**
Quest 2 with steam, using virtual desktop

**Describe the bug**
The custom song button does not appear in multiplayer in log file i can see 'MultiplayerExtensions' is missing depencency 'BeatSaverSharp@^2.0.1'i have mod assistant and i have 3.0.2

**To Reproduce**

**Expected behavior**
The custom button does not show, i uninstalled and installed the mod, restarted pc, vr, nothing helps

**Log**
The log file from the game session the issue occurred (restarting the game creates a new log file). 
The log file can be found at `Beat Saber\Logs\_latest.log` (`Beat Saber` being the folder `Beat Saber.exe` is in). You can drag-and-drop it into the Issue.
[_latest.log](https://github.com/Goobwabber/MultiplayerExtensions/files/7384684/_latest.log)

**Screenshots/Video**

**Additional context**
Tried to find solution, i have a friend and both of us have the same problem, neither of us can figure it out, we tried everything from the Troubleshooting tab too, he just downloaded beatsaber, he just bought it so he's fresh too

**Comment by hax4dazy** [comment] 2021-10-21 01:09
Mate, you gave no info. If you're trying to run this on the latest version of the game you can't. See #136

**Comment by Goobwabber** [comment] 2021-10-29 18:52
Duplicate of #136

**Closed by Goobwabber** 2021-10-29 18:52 UTC
